#!/bin/sh

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2018-present Team CoreELEC (https://coreelec.org)

$TOOLCHAIN/bin/mkimage -C none -T ramdisk -A arm64 -d $INSTALL/../initramfs.cpio $INSTALL/usr/share/bootloader/uInitrd

mkdir -p $RELEASE_DIR/3rdparty/bootloader
  cp -a $INSTALL/usr/share/bootloader/* $RELEASE_DIR/3rdparty/bootloader
